# -*- coding: utf-8 -*-
# Objective: Service-layer helpers for router services.
"""Shared helpers for router_core routing/feedback/maintenance."""

from __future__ import annotations

import math
from typing import Any, Dict, Optional, Tuple


def normalize_modality(modality: str, image_b64: Optional[str]) -> str:
    """Normalize the request modality used by routing and provider selection.

    The router accepts a declared modality from the request layer, but some
    callers still send ``text`` while also attaching an image payload. This
    helper converts that ambiguous combination into the effective runtime
    modality expected by downstream services.

    Args:
        modality: The modality declared by the caller.
        image_b64: Optional base64-encoded image payload attached to the request.

    Returns:
        str: ``vision`` when an image is present alongside ``text``; otherwise
        the original modality or ``text`` when the input is empty.
    """
    m = modality or "text"
    if bool(image_b64) and m == "text":
        return "vision"
    return m


def build_final_prompt(
    query: str,
    system_prompt: str,
    use_rag: bool,
    rag_text: Optional[str],
) -> str:
    """Build the final prompt sent to the selected model.

    When retrieval-augmented generation is enabled, the router may replace the
    original query with retrieved context or an already-augmented prompt. This
    helper applies the system prompt consistently for both RAG and non-RAG
    flows, so provider adapters receive a single normalized prompt string.

    Args:
        query: Original user query.
        system_prompt: Optional system instruction configured for the request.
        use_rag: Whether retrieved context should be preferred over the raw
            query.
        rag_text: Retrieved or augmented text generated by the RAG pipeline.

    Returns:
        str: The final prompt payload ready for model invocation.
    """
    if use_rag:
        if rag_text is None:
            rag_text = query
        if system_prompt:
            return f"{system_prompt}\n\nUsuário: {rag_text}".strip()
        return rag_text

    if system_prompt:
        return f"{system_prompt}\n\nUsuário: {query}".strip()
    return query


def parse_meta_cost(
    meta: Any,
    chosen_model: str,
    cost_lookup,
) -> Tuple[int, int, float, float, Dict[str, Any]]:
    """Extract token, cost, and load-time information from provider metadata.

    Providers do not always return a fully normalized metadata payload. This
    helper accepts loosely structured metadata, extracts the fields the router
    needs for accounting, and falls back to a pricing lookup when an explicit
    cost value is not present.

    Args:
        meta: Provider metadata payload, typically a dictionary.
        chosen_model: Fully qualified model name used for pricing fallback.
        cost_lookup: Callable that estimates total cost from model and token
            counts.

    Returns:
        tuple[int, int, float, float, dict[str, Any]]: Prompt tokens, completion
        tokens, total estimated cost, model load time in seconds, and a sanitized
        metadata dictionary safe for downstream consumers.
    """
    p_tok = 0
    c_tok = 0
    total_cost = 0.0
    load_time_s = 0.0

    if isinstance(meta, dict):
        load_time_s = float(meta.get("load_time", 0.0) or 0.0)
        p_tok = int(meta.get("prompt_tokens", 0) or 0)
        c_tok = int(meta.get("completion_tokens", 0) or 0)

        if meta.get("cost_per_1k") is not None and float(meta.get("cost_per_1k", 0)) > 0:
            total_cost = float(meta["cost_per_1k"])
        else:
            try:
                total_cost = float(cost_lookup(chosen_model, p_tok, c_tok))
            except Exception:
                total_cost = 0.0

    meta_safe = meta if isinstance(meta, dict) else {}
    return p_tok, c_tok, total_cost, load_time_s, meta_safe


def should_enable_dedup(settings_get, requested: bool) -> bool:
    """Resolve whether request deduplication should run for the current call.

    Deduplication is only enabled when both the caller requested it and the
    runtime setting allows it. This avoids activating the feature implicitly
    during incident response or local debugging.
    """
    return requested and str(settings_get("REQUEST_DEDUP_ENABLED", "0")).strip() in ("1", "true", "True")


def compute_judge_probability(
    n_samples: int,
    predicted_error_prob: float,
    chosen_model: str,
    min_sample_rate: float,
) -> float:
    """Compute the probability of sending a response through the judge pipeline.

    The router uses a mix of warm-up behavior, learned error probability, and
    model-specific heuristics to decide when judging is worth the extra cost.
    New or poorly observed responses are judged more aggressively, while models
    considered high-end receive a lower sampling rate.

    Args:
        n_samples: Number of historical samples for the chosen model.
        predicted_error_prob: Estimated probability that the answer is low
            quality or risky.
        chosen_model: Fully qualified model name used for heuristic discounts.
        min_sample_rate: Minimum judging rate enforced by configuration.

    Returns:
        float: Sampling probability constrained to be at least the configured
        minimum rate.
    """
    if n_samples < 5:
        base_prob = 1.0
    else:
        base_prob = 1.0 / math.sqrt(n_samples)

    prob_judge = max(base_prob, predicted_error_prob)

    if "gpt-5" in chosen_model or "gpt-4" in chosen_model or "claude" in chosen_model:
        prob_judge *= 0.1

    return max(min_sample_rate, prob_judge)
