from locust import HttpUser, task, between
import random

QUERIES = [
    # ===========================
    # 🏛️ Fatos Históricos (40)
    # ===========================
    {"query": "Explique as causas da Primeira Guerra Mundial."},
    {"query": "Quais foram os principais eventos da Revolução Francesa?"},
    {"query": "Quem foi Napoleão Bonaparte e qual seu impacto na Europa?"},
    {"query": "Resumo sobre a Independência do Brasil."},
    {"query": "Explique o que foi o Iluminismo."},
    {"query": "O que motivou a Revolução Industrial na Inglaterra?"},
    {"query": "Quem foi Mahatma Gandhi e por que ele é importante?"},
    {"query": "O que foi o Muro de Berlim e quando caiu?"},
    {"query": "O que foi a Guerra Fria e quem foram os principais envolvidos?"},
    {"query": "O que marcou a Era Vargas no Brasil?"},
    {"query": "Descreva o papel da ONU após a Segunda Guerra Mundial."},
    {"query": "Explique o que foi a Ditadura Militar no Brasil."},
    {"query": "Quem foi Getúlio Vargas?"},
    {"query": "O que foi o Tratado de Versalhes?"},
    {"query": "Explique a corrida espacial entre EUA e URSS."},
    {"query": "O que foi o Renascimento e por que foi importante?"},
    {"query": "Quem foi Leonardo da Vinci e suas principais contribuições?"},
    {"query": "Explique as Cruzadas medievais."},
    {"query": "O que foi o Feudalismo e suas características principais?"},
    {"query": "Qual a importância da Revolução Russa de 1917?"},
    {"query": "Explique o que foi o Apartheid na África do Sul."},
    {"query": "Quem foi Nelson Mandela e qual sua importância histórica?"},
    {"query": "O que foi a Inquisição e qual seu papel na história da Igreja?"},
    {"query": "Explique o conceito de imperialismo no século XIX."},
    {"query": "Quais foram os principais navegadores das Grandes Navegações?"},
    {"query": "O que foi a Revolução Cubana e quem a liderou?"},
    {"query": "Explique o contexto da independência dos Estados Unidos."},
    {"query": "O que foi o Holocausto e qual seu impacto histórico?"},
    {"query": "Explique o movimento sufragista feminino."},
    {"query": "Quem foi Dom Pedro II e qual sua importância no Brasil?"},
    {"query": "O que representou o Plano Marshall na Europa pós-guerra?"},
    {"query": "Quem foi Karl Marx e qual sua influência histórica?"},
    {"query": "Explique o que foi o Vietnã na Guerra Fria."},
    {"query": "Quais foram as principais invenções do século XX?"},
    {"query": "Descreva a história da formação da União Europeia."},
    {"query": "Explique o que foi a Revolução Mexicana."},
    {"query": "Quem foi Che Guevara e qual seu legado?"},
    {"query": "Explique o papel das mulheres durante a Segunda Guerra Mundial."},
    {"query": "Quais foram os principais feitos de Dom Pedro I?"},
    {"query": "O que foi o AI-5 no Brasil?"},
    
    # ===========================
    # 💻 Programação / Código (40)
    # ===========================
    {"query": "Escreva um código Python para inverter uma string."},
    {"query": "Explique o que é uma função lambda em Python."},
    {"query": "Como criar uma classe em Python?"},
    {"query": "Escreva um script Python que leia um arquivo CSV e calcule a média."},
    {"query": "O que é uma exceção em Python e como tratá-la?"},
    {"query": "Explique o conceito de herança em programação orientada a objetos."},
    {"query": "Escreva um programa em C que calcule o fatorial de um número."},
    {"query": "Explique o que é recursão e dê um exemplo."},
    {"query": "Escreva um código JavaScript para somar os elementos de uma lista."},
    {"query": "O que é uma API REST e como funciona?"},
    {"query": "Explique o conceito de variável imutável."},
    {"query": "Escreva um script Python que consome uma API e imprime o JSON."},
    {"query": "O que é um dicionário em Python e como iterar sobre ele?"},
    {"query": "Explique a diferença entre lista, tupla e conjunto em Python."},
    {"query": "Como usar o pandas para agrupar dados?"},
    {"query": "Escreva um código SQL para selecionar alunos com nota > 8."},
    {"query": "Explique o que é um container Docker."},
    {"query": "Como criar uma API com FastAPI em Python?"},
    {"query": "O que é asyncio em Python e quando usar?"},
    {"query": "Explique a diferença entre process e thread."},
    {"query": "O que é uma promise em JavaScript?"},
    {"query": "Como tratar exceções em Java?"},
    {"query": "Escreva um script para converter JSON em CSV."},
    {"query": "Explique o conceito de garbage collector."},
    {"query": "O que é ORM e cite um exemplo em Python."},
    {"query": "Escreva uma função Python que calcule o número de Fibonacci."},
    {"query": "Explique o que é um webhook."},
    {"query": "Como criar um container Docker a partir de um Dockerfile?"},
    {"query": "Escreva um script Python que faça scraping de um site."},
    {"query": "Explique a diferença entre GET e POST."},
    {"query": "O que é uma expressão regular e como usá-la em Python?"},
    {"query": "Como implementar um servidor HTTP básico em Python?"},
    {"query": "Explique a função map() e filter() em Python."},
    {"query": "Como usar o módulo logging em Python?"},
    {"query": "Escreva um script Bash para copiar arquivos modificados nas últimas 24h."},
    {"query": "Explique o que é CI/CD e sua importância."},
    {"query": "Escreva um programa Python para detectar palavras duplicadas em um texto."},
    {"query": "Explique o conceito de API Gateway."},
    {"query": "O que é um token JWT e como funciona?"},
    {"query": "Explique o que é programação reativa."},

    # ===========================
    # ⚛️ Física (40)
    # ===========================
    {"query": "Explique a lei da gravitação universal de Newton."},
    {"query": "O que é a teoria da relatividade de Einstein?"},
    {"query": "Explique o conceito de energia cinética."},
    {"query": "O que é movimento uniformemente acelerado?"},
    {"query": "Explique a diferença entre massa e peso."},
    {"query": "O que é um campo magnético?"},
    {"query": "Explique o que é entropia na termodinâmica."},
    {"query": "O que é o princípio da inércia?"},
    {"query": "Explique o conceito de trabalho e potência."},
    {"query": "O que é a lei de Coulomb?"},
    {"query": "Explique a diferença entre corrente contínua e alternada."},
    {"query": "O que é o efeito fotoelétrico?"},
    {"query": "Explique o conceito de torque."},
    {"query": "O que é o momento linear?"},
    {"query": "Explique o conceito de impulso."},
    {"query": "O que é a força centrípeta?"},
    {"query": "Explique o conceito de ondas mecânicas."},
    {"query": "O que é o som e como ele se propaga?"},
    {"query": "Explique a diferença entre reflexão e refração da luz."},
    {"query": "O que é o espectro eletromagnético?"},
    {"query": "Explique a diferença entre calor e temperatura."},
    {"query": "O que é a segunda lei da termodinâmica?"},
    {"query": "Explique o conceito de campo elétrico."},
    {"query": "O que é um circuito elétrico simples?"},
    {"query": "Explique o conceito de resistência elétrica."},
    {"query": "O que é o princípio de Arquimedes?"},
    {"query": "Explique o conceito de densidade e sua fórmula."},
    {"query": "O que é a força de atrito e como ela atua?"},
    {"query": "Explique o funcionamento de um transformador elétrico."},
    {"query": "O que é energia potencial gravitacional?"},
    {"query": "Explique o que é ressonância em sistemas oscilatórios."},
    {"query": "O que é o efeito Doppler?"},
    {"query": "Explique o conceito de corrente elétrica."},
    {"query": "O que é a lei de Ohm?"},
    {"query": "Explique o funcionamento de um motor elétrico."},
    {"query": "O que é o campo gravitacional?"},
    {"query": "Explique o princípio da conservação da energia."},
    {"query": "O que é uma onda sonora?"},
    {"query": "Explique o que é pressão e como é medida."},
    {"query": "O que é a energia nuclear?"},
    
    # ===========================
    # 🧪 Química (40)
    # ===========================
    {"query": "Explique o conceito de ligação covalente."},
    {"query": "O que é um átomo e quais são suas partículas?"},
    {"query": "Explique a diferença entre ácido e base."},
    {"query": "O que é uma reação de oxirredução?"},
    {"query": "Explique o que é a tabela periódica."},
    {"query": "O que é uma ligação iônica?"},
    {"query": "Explique o conceito de mol."},
    {"query": "O que é uma reação endotérmica?"},
    {"query": "Explique o conceito de catalisador."},
    {"query": "O que é pH e como ele é calculado?"},
    {"query": "Explique o conceito de concentração molar."},
    {"query": "O que é uma reação de neutralização?"},
    {"query": "Explique o conceito de eletrólito."},
    {"query": "O que é uma mistura homogênea e heterogênea?"},
    {"query": "Explique o conceito de polaridade."},
    {"query": "O que é uma reação de combustão?"},
    {"query": "Explique o conceito de estequiometria."},
    {"query": "O que é uma substância pura?"},
    {"query": "Explique o conceito de isotopia."},
    {"query": "O que é uma reação de dupla troca?"},
    {"query": "Explique o conceito de equilíbrio químico."},
    {"query": "O que é uma ligação metálica?"},
    {"query": "Explique o conceito de solubilidade."},
    {"query": "O que é o número atômico e o número de massa?"},
    {"query": "Explique a diferença entre elemento e composto químico."},
    {"query": "O que é uma reação de decomposição?"},
    {"query": "Explique o conceito de eletronegatividade."},
    {"query": "O que é uma reação de síntese?"},
    {"query": "Explique o conceito de pressão osmótica."},
    {"query": "O que é uma solução saturada?"},
    {"query": "Explique o conceito de ponto de fusão."},
    {"query": "O que é uma substância anfótera?"},
    {"query": "Explique o conceito de densidade química."},
    {"query": "O que é uma reação exotérmica?"},
    {"query": "Explique o conceito de átomo neutro."},
    {"query": "O que é uma reação reversível?"},
    {"query": "Explique o conceito de energia de ativação."},
    {"query": "O que é uma solução tampão?"},
    {"query": "Explique o conceito de oxidação."},
    {"query": "O que é o princípio de Le Chatelier?"},
    
    # ===========================
    # 📄 Documentação / Boas práticas (40)
    # ===========================
    {"query": "Explique o que é um README e sua importância."},
    {"query": "Quais são as boas práticas de documentação de código?"},
    {"query": "Explique o que é versionamento semântico."},
    {"query": "Como documentar uma API REST?"},
    {"query": "O que é um changelog e para que serve?"},
    {"query": "Explique o que é um docstring em Python."},
    {"query": "Como gerar documentação automática com Sphinx?"},
    {"query": "O que é o padrão OpenAPI (Swagger)?"},
    {"query": "Explique como escrever comentários úteis no código."},
    {"query": "O que deve conter um manual de usuário técnico?"},
    {"query": "Explique o conceito de código autoexplicativo."},
    {"query": "Como documentar um pipeline de CI/CD?"},
    {"query": "Explique o que é uma especificação funcional."},
    {"query": "Como descrever requisitos não funcionais?"},
    {"query": "Explique o que é uma arquitetura de software."},
    {"query": "Como criar diagramas UML para documentação?"},
    {"query": "Explique o que é um backlog de produto."},
    {"query": "Como organizar a documentação de um projeto open-source?"},
    {"query": "Explique o que é uma política de commits."},
    {"query": "Como usar o GitHub Wiki para documentar projetos?"},
    {"query": "Explique o conceito de onboarding técnico."},
    {"query": "Como descrever dependências em um projeto Python?"},
    {"query": "O que é um arquivo requirements.txt?"},
    {"query": "Explique o papel de um README técnico."},
    {"query": "Como manter a documentação sempre atualizada?"},
    {"query": "Explique o conceito de documentação viva."},
    {"query": "Como criar documentação com MkDocs?"},
    {"query": "Explique o que é um ADR (Architectural Decision Record)."},
    {"query": "Como documentar endpoints em uma API?"},
    {"query": "Explique o conceito de boas práticas de código limpo."},
    {"query": "Como usar o padrão de docstring Google?"},
    {"query": "Explique o que é documentação orientada ao usuário."},
    {"query": "Como documentar testes automatizados?"},
    {"query": "Explique o conceito de README interativo."},
    {"query": "Como criar exemplos de uso em documentação técnica?"},
    {"query": "Explique o papel dos diagramas de sequência."},
    {"query": "Como documentar ambientes de execução (dev/prod)?"},
    {"query": "Explique o que é documentação de infraestrutura como código."},
    {"query": "Como usar o Doxygen para projetos C/C++?"},
    {"query": "Explique o conceito de documentação mínima viável."},
]



class RouterUser(HttpUser):
    wait_time = between(1, 3)
    host = "http://llm_router_api:8000"

    @task
    def send_query(self):
        payload = {
            "query": "Explique o conceito de NSGA-II",
            "enable_rag_for_answer": False,
            "max_tokens": 256,
            "temperature": 0.3
        }
        self.client.post("/query", json=payload)
