from locust import HttpUser, task, between
import random

# ==========================================================
# 475 CONSULTAS DIVERSIFICADAS — 19 TEMAS
# ==========================================================

QUERIES = [

    # ======================================================
    # 🏛️ História (25)
    # ======================================================
    {"query": "Explique as causas da Primeira Guerra Mundial."},
    {"query": "O que foi a Revolução Francesa e seus efeitos políticos?"},
    {"query": "Quem foi Napoleão Bonaparte e qual seu impacto histórico?"},
    {"query": "Resuma a Independência do Brasil."},
    {"query": "Explique o que foi o Iluminismo."},
    {"query": "O que motivou a Revolução Industrial na Inglaterra?"},
    {"query": "Quem foi Mahatma Gandhi e sua importância histórica?"},
    {"query": "O que foi o Muro de Berlim e quando caiu?"},
    {"query": "O que foi a Guerra Fria e seus principais eventos?"},
    {"query": "O que caracterizou a Era Vargas no Brasil?"},
    {"query": "Qual foi o papel da ONU após a Segunda Guerra Mundial?"},
    {"query": "Explique a Ditadura Militar no Brasil."},
    {"query": "Quem foi Getúlio Vargas?"},
    {"query": "O que foi o Tratado de Versalhes?"},
    {"query": "Explique a corrida espacial entre EUA e URSS."},
    {"query": "O que foi o Renascimento Cultural e suas características?"},
    {"query": "Quem foi Leonardo da Vinci e sua importância?"},
    {"query": "Explique as Cruzadas."},
    {"query": "O que foi o Feudalismo e suas relações sociais?"},
    {"query": "Qual a importância da Revolução Russa de 1917?"},
    {"query": "O que foi o Apartheid e quem foi Nelson Mandela?"},
    {"query": "Explique a Inquisição e seu papel histórico."},
    {"query": "O que foi o imperialismo europeu?"},
    {"query": "Quais foram os principais navegadores das Grandes Navegações?"},
    {"query": "O que foi a Revolução Cubana?"},

    # ======================================================
    # 💻 Programação (25)
    # ======================================================
    {"query": "Escreva um código Python que inverte uma string."},
    {"query": "Explique o conceito de função lambda."},
    {"query": "O que é uma classe em Python?"},
    {"query": "Como tratar exceções em Python?"},
    {"query": "Explique o conceito de herança na OOP."},
    {"query": "Escreva um programa que calcule o fatorial em C."},
    {"query": "Explique o que é recursão."},
    {"query": "Escreva um código JavaScript que soma elementos de uma lista."},
    {"query": "O que é uma API REST?"},
    {"query": "Explique o conceito de variável imutável."},
    {"query": "O que é um dicionário em Python?"},
    {"query": "Explique a diferença entre lista, tupla e conjunto."},
    {"query": "Como usar pandas para agrupar dados?"},
    {"query": "Escreva um SQL para selecionar alunos com nota > 8."},
    {"query": "Explique o que é um container Docker."},
    {"query": "Como criar uma API com FastAPI?"},
    {"query": "O que é asyncio em Python?"},
    {"query": "Explique a diferença entre process e thread."},
    {"query": "O que é um webhook?"},
    {"query": "Como criar um Dockerfile básico?"},
    {"query": "Escreva um script Python que faz scraping de um site."},
    {"query": "Explique a diferença entre GET e POST."},
    {"query": "O que é uma expressão regular e como usá-la?"},
    {"query": "Como usar o módulo logging em Python?"},
    {"query": "Explique o conceito de CI/CD."},

    # ======================================================
    # ⚛️ Física (25)
    # ======================================================
    {"query": "Explique a lei da gravitação universal."},
    {"query": "O que é a teoria da relatividade?"},
    {"query": "Explique o conceito de energia cinética."},
    {"query": "O que é movimento uniformemente acelerado?"},
    {"query": "Explique a diferença entre massa e peso."},
    {"query": "O que é um campo magnético?"},
    {"query": "Explique o conceito de entropia."},
    {"query": "O que é o princípio da inércia?"},
    {"query": "Explique o conceito de trabalho e potência."},
    {"query": "O que é a lei de Coulomb?"},
    {"query": "Explique a diferença entre corrente contínua e alternada."},
    {"query": "O que é o efeito fotoelétrico?"},
    {"query": "Explique o conceito de torque."},
    {"query": "O que é o momento linear?"},
    {"query": "Explique o conceito de impulso."},
    {"query": "O que é a força centrípeta?"},
    {"query": "Explique o conceito de ondas mecânicas."},
    {"query": "O que é o som e como ele se propaga?"},
    {"query": "Explique a diferença entre reflexão e refração da luz."},
    {"query": "O que é o espectro eletromagnético?"},
    {"query": "Explique o conceito de calor e temperatura."},
    {"query": "O que é o princípio de Arquimedes?"},
    {"query": "Explique o funcionamento de um transformador elétrico."},
    {"query": "O que é energia potencial gravitacional?"},
    {"query": "Explique o conceito de pressão e como é medida."},

    # ======================================================
    # 🧪 Química (25)
    # ======================================================
    {"query": "Explique o conceito de ligação covalente."},
    {"query": "O que é um átomo e suas partículas?"},
    {"query": "Explique a diferença entre ácido e base."},
    {"query": "O que é uma reação de oxirredução?"},
    {"query": "Explique a tabela periódica."},
    {"query": "O que é uma ligação iônica?"},
    {"query": "Explique o conceito de mol."},
    {"query": "O que é uma reação endotérmica?"},
    {"query": "Explique o conceito de catalisador."},
    {"query": "O que é pH e como calculá-lo?"},
    {"query": "Explique o conceito de concentração molar."},
    {"query": "O que é uma reação de neutralização?"},
    {"query": "Explique o conceito de eletrólito."},
    {"query": "O que é uma mistura homogênea?"},
    {"query": "Explique o conceito de polaridade."},
    {"query": "O que é uma reação de combustão?"},
    {"query": "Explique o conceito de estequiometria."},
    {"query": "O que é uma substância pura?"},
    {"query": "Explique o conceito de isotopia."},
    {"query": "O que é uma reação de dupla troca?"},
    {"query": "Explique o conceito de equilíbrio químico."},
    {"query": "O que é uma ligação metálica?"},
    {"query": "Explique o conceito de solubilidade."},
    {"query": "O que é o número atômico?"},
    {"query": "Explique a diferença entre elemento e composto químico."},

    # ======================================================
    # 📊 Matemática (25)
    # ======================================================
    {"query": "Explique o teorema de Pitágoras."},
    {"query": "O que é uma progressão aritmética?"},
    {"query": "Explique o conceito de função exponencial."},
    {"query": "O que é um número primo?"},
    {"query": "Explique o conceito de derivada."},
    {"query": "O que é uma integral?"},
    {"query": "Explique o que é limite em cálculo."},
    {"query": "O que é uma matriz e como multiplicar?"},
    {"query": "Explique o conceito de determinante."},
    {"query": "O que é uma função quadrática?"},
    {"query": "Explique o conceito de probabilidade."},
    {"query": "O que é média, mediana e moda?"},
    {"query": "Explique o conceito de vetor."},
    {"query": "O que é um logaritmo?"},
    {"query": "Explique o conceito de geometria analítica."},
    {"query": "O que é um gráfico de função linear?"},
    {"query": "Explique o conceito de seno e cosseno."},
    {"query": "O que é trigonometria?"},
    {"query": "Explique o conceito de desigualdade."},
    {"query": "O que é uma equação diferencial?"},
    {"query": "Explique o conceito de sequência numérica."},
    {"query": "O que é o teorema de Tales?"},
    {"query": "Explique o conceito de área e volume."},
    {"query": "O que é análise combinatória?"},
    {"query": "Explique o conceito de estatística descritiva."},

    # ======================================================
    # 🌾 Agronegócio e IoT (25)
    # ======================================================
    {"query": "Explique o conceito de automação agrícola."},
    {"query": "O que é um sensor de umidade do solo?"},
    {"query": "Explique como funciona um sistema de irrigação automática."},
    {"query": "O que é um ESP32 e como aplicá-lo na agricultura?"},
    {"query": "Explique o conceito de Internet das Coisas (IoT)."},
    {"query": "O que é um microcontrolador?"},
    {"query": "Explique como usar um sensor DHT22."},
    {"query": "O que é MQTT e como aplicá-lo em fazendas inteligentes?"},
    {"query": "Explique o conceito de automação em aviários."},
    {"query": "O que é um pressostato?"},
    {"query": "Explique o papel dos relés em automação rural."},
    {"query": "O que é uma bomba submersa e como controlá-la?"},
    {"query": "Explique o conceito de sensoriamento remoto."},
    {"query": "O que é uma válvula solenoide?"},
    {"query": "Explique como usar um RTC em um projeto IoT."},
    {"query": "O que é um servidor NTP e por que é importante?"},
    {"query": "Explique o conceito de fotoperíodo em galinhas poedeiras."},
    {"query": "O que é um sistema de climatização de aviário?"},
    {"query": "Explique como medir temperatura e umidade no campo."},
    {"query": "O que é uma fonte de alimentação estabilizada?"},
    {"query": "Explique como controlar motores com ESP32."},
    {"query": "O que é uma rede LoRaWAN?"},
    {"query": "Explique o conceito de telemetria agrícola."},
    {"query": "O que é um sensor de amônia?"},
    {"query": "Explique o conceito de manutenção preditiva no campo."},

    # ======================================================
    # 🌎 Geografia (25)
    # ======================================================
    {"query": "Explique o processo de desertificação."},
    {"query": "O que é o efeito estufa?"},
    {"query": "Explique as causas do aquecimento global."},
    {"query": "O que são biomas e cite exemplos brasileiros."},
    {"query": "Explique a diferença entre latitude e longitude."},
    {"query": "O que é um mapa topográfico?"},
    {"query": "Explique o ciclo da água."},
    {"query": "O que é a erosão do solo e como evitá-la?"},
    {"query": "Explique a formação de terremotos."},
    {"query": "O que é um vulcão ativo?"},
    {"query": "Explique o conceito de urbanização."},
    {"query": "O que é um rio perene e um rio intermitente?"},
    {"query": "Explique o desmatamento e seus impactos."},
    {"query": "O que é um clima tropical?"},
    {"query": "Explique o conceito de fronteira geopolítica."},
    {"query": "O que é a globalização?"},
    {"query": "Explique a diferença entre migração e imigração."},
    {"query": "O que é a poluição atmosférica?"},
    {"query": "Explique o conceito de relevo."},
    {"query": "O que é o aquecimento das correntes marítimas?"},
    {"query": "Explique a formação das montanhas."},
    {"query": "O que é um recurso natural renovável?"},
    {"query": "Explique o conceito de latitude."},
    {"query": "O que é um terremoto e como é medido?"},
    {"query": "Explique o impacto das mudanças climáticas."},

    # ======================================================
    # 📡 Redes e Infraestrutura (25)
    # ======================================================
    {"query": "Explique o que é o protocolo TCP/IP."},
    {"query": "O que é DNS e como ele funciona?"},
    {"query": "Explique o conceito de sub-rede."},
    {"query": "O que é NAT e por que é usado?"},
    {"query": "Explique o funcionamento de um roteador."},
    {"query": "O que é DHCP?"},
    {"query": "Explique o conceito de VLAN."},
    {"query": "O que é IPv6?"},
    {"query": "Explique o modelo OSI e suas camadas."},
    {"query": "O que é uma VPN?"},
    {"query": "Explique o conceito de firewall."},
    {"query": "O que é SNMP?"},
    {"query": "Explique o conceito de proxy reverso."},
    {"query": "O que é SSL/TLS?"},
    {"query": "Explique o conceito de latência."},
    {"query": "O que é jitter em redes?"},
    {"query": "Explique o conceito de QoS."},
    {"query": "O que é um switch gerenciável?"},
    {"query": "Explique a diferença entre hub e switch."},
    {"query": "O que é routing estático e dinâmico?"},
    {"query": "Explique o funcionamento do BGP."},
    {"query": "O que é um balanceador de carga?"},
    {"query": "Explique o conceito de DNS local."},
    {"query": "O que é IPv4 e por que está se esgotando?"},
    {"query": "Explique o que é tunneling em redes."},

    # ======================================================
    # ⚙️ Inteligência Artificial e Machine Learning (25)
    # ======================================================
    {"query": "Explique o que é aprendizado supervisionado."},
    {"query": "O que é uma rede neural convolucional?"},
    {"query": "Explique o conceito de overfitting."},
    {"query": "O que é um dataset balanceado?"},
    {"query": "Explique o algoritmo KNN."},
    {"query": "O que é regressão linear?"},
    {"query": "Explique o que é um modelo de linguagem."},
    {"query": "O que é reinforcement learning?"},
    {"query": "Explique o conceito de embeddings."},
    {"query": "O que é um modelo transformer?"},
    {"query": "Explique o funcionamento do GPT."},
    {"query": "O que é fine-tuning de modelo?"},
    {"query": "Explique o conceito de atenção em redes neurais."},
    {"query": "O que é um token em LLMs?"},
    {"query": "Explique o conceito de RLHF."},
    {"query": "O que é o algoritmo NSGA-II?"},
    {"query": "Explique o conceito de multi-objective optimization."},
    {"query": "O que é backpropagation?"},
    {"query": "Explique o conceito de perda cruzada (cross entropy)."},
    {"query": "O que é regularização L2?"},
    {"query": "Explique o que é batch normalization."},
    {"query": "O que é aprendizado não supervisionado?"},
    {"query": "Explique o conceito de clustering."},
    {"query": "O que é PCA?"},
    {"query": "Explique o que é gradient descent."},

    # ======================================================
    # 🧬 Biologia e Saúde (25)
    # ======================================================
    {"query": "Explique a estrutura de uma célula eucariótica."},
    {"query": "O que é o DNA e qual sua função?"},
    {"query": "Diferencie mitose de meiose."},
    {"query": "O que é a fotossíntese?"},
    {"query": "Descreva o sistema nervoso humano."},
    {"query": "O que é um vírus e como ele se replica?"},
    {"query": "Como as vacinas funcionam?"},
    {"query": "O que são antibióticos e como agem?"},
    {"query": "Explique o processo da respiração celular."},
    {"query": "Descreva o sistema digestivo humano."},
    {"query": "O que é metabolismo?"},
    {"query": "Explique os conceitos básicos da genética Mendeliana."},
    {"query": "O que é a teoria da evolução de Darwin?"},
    {"query": "O que é seleção natural?"},
    {"query": "Defina ecossistema e cadeia alimentar."},
    {"query": "Descreva o sistema circulatório humano."},
    {"query": "O que é homeostase?"},
    {"query": "Qual a função das proteínas no corpo humano?"},
    {"query": "O que é uma enzima?"},
    {"query": "Quais são os principais órgãos do corpo humano e suas funções?"},
    {"query": "Como funciona o sistema imunológico?"},
    {"query": "O que é uma pandemia?"},
    {"query": "Diferencie bactérias de vírus."},
    {"query": "O que é uma dieta balanceada?"},
    {"query": "Quais os riscos do sedentarismo para a saúde?"},

    # ======================================================
    # 📈 Economia e Finanças (25)
    # ======================================================
    {"query": "O que é inflação e quais suas causas?"},
    {"query": "Defina PIB (Produto Interno Bruto)."},
    {"query": "Explique o que é política monetária."},
    {"query": "Diferencie política fiscal de política monetária."},
    {"query": "O que é a lei da oferta e da procura?"},
    {"query": "Como funciona a bolsa de valores?"},
    {"query": "O que significa 'bear market' e 'bull market'?"},
    {"query": "O que é uma criptomoeda?"},
    {"query": "Explique a importância da diversificação de investimentos."},
    {"query": "Diferencie juros simples de juros compostos."},
    {"query": "O que é um fundo mútuo?"},
    {"query": "O que é um ETF (Exchange Traded Fund)?"},
    {"query": "Como calcular o ROI (Retorno sobre Investimento)?"},
    {"query": "Diferencie microeconomia de macroeconomia."},
    {"query": "Qual o papel do Banco Central?"},
    {"query": "O que caracteriza uma recessão econômica?"},
    {"query": "O que é a 'mão invisível' de Adam Smith?"},
    {"query": "Explique a teoria econômica Keynesiana."},
    {"query": "Como criar um orçamento pessoal eficaz?"},
    {"query": "O que é 'spread' bancário?"},
    {"query": "O que é uma hipoteca?"},
    {"query": "O que são dividendos de ações?"},
    {"query": "Explique o que é taxa de câmbio."},
    {"query": "O que é o Tesouro Direto?"},
    {"query": "Quais os diferentes tipos de impostos?"},

    # ======================================================
    # 📚 Literatura e Gramática (25)
    # ======================================================
    {"query": "Quem foi William Shakespeare e qual sua principal obra?"},
    {"query": "Faça um breve resumo do livro 'Dom Quixote'."},
    {"query": "O que é uma metáfora? Dê exemplos."},
    {"query": "Diferencie metáfora de símile (comparação)."},
    {"query": "O que foi o Modernismo na literatura brasileira?"},
    {"query": "Cite três autores do Romantismo no Brasil."},
    {"query": "Quem foi Machado de Assis? Resuma 'Dom Casmurro'."},
    {"query": "Qual a diferença entre 'mas' e 'mais'?"},
    {"query": "O que é um sujeito oculto (elíptico)?"},
    {"query": "Explique o que é um verbo e seus tempos."},
    {"query": "Diferencie adjetivo de advérbio."},
    {"query": "Explique as regras de uso da crase em português."},
    {"query": "Quando usar 'por que', 'porque', 'porquê' e 'por quê'?"},
    {"query": "O que é um soneto?"},
    {"query": "O que é um haicai?"},
    {"query": "Explique o que é o Realismo Mágico na literatura."},
    {"query": "Quem foi Gabriel García Márquez?"},
    {"query": "Resuma a 'Odisseia' de Homero."},
    {"query": "O que é uma distopia literária? Dê exemplos."},
    {"query": "Quem foi Clarice Lispector e qual seu estilo?"},
    {"query": "O que são figuras de linguagem? Cite 3 tipos."},
    {"query": "O que é aliteração?"},
    {"query": "Diferencie voz ativa, voz passiva e voz reflexiva."},
    {"query": "O que é coesão e coerência textual?"},
    {"query": "Quem foi Camões e qual sua obra mais famosa?"},

    # ======================================================
    # 🧠 Filosofia e Sociologia (25)
    # ======================================================
    {"query": "O que é o 'Mito da Caverna' de Platão?"},
    {"query": "Explique o método socrático."},
    {"query": "Quem foi Aristóteles e o que é a 'ética a Nicômaco'?"},
    {"query": "O que é o 'Contrato Social' de Rousseau?"},
    {"query": "Quem foi Karl Marx e o que é o materialismo histórico?"},
    {"query": "Explique a frase 'Penso, logo existo' de Descartes."},
    {"query": "O que é o existencialismo de Sartre?"},
    {"query": "Quem foi Nietzsche e o que é o 'super-homem' (Übermensch)?"},
    {"query": "O que é o utilitarismo?"},
    {"query": "Quem foi Max Weber e o que é a 'jaula de ferro'?"},
    {"query": "O que é 'fato social' para Durkheim?"},
    {"query": "Explique o que é a 'Indústria Cultural' para Adorno e Horkheimer."},
    {"query": "O que é o conceito de 'habitus' em Pierre Bourdieu?"},
    {"query": "Quem foi Michel Foucault e o que é 'microfísica do poder'?"},
    {"query": "O que é o 'imperativo categórico' de Kant?"},
    {"query": "Diferencie 'ser' e 'dever-ser' na filosofia."},
    {"query": "O que é a 'banalidade do mal' de Hannah Arendt?"},
    {"query": "Explique o que é o 'estado de natureza' em Hobbes."},
    {"query": "O que é a globalização na perspectiva sociológica?"},
    {"query": "O que é estratificação social?"},
    {"query": "Explique o conceito de 'modernidade líquida' de Bauman."},
    {"query": "O que é o positivismo de Auguste Comte?"},
    {"query": "Quem foi Simone de Beauvoir e qual sua principal ideia?"},
    {"query": "O que é o conceito de 'alienação' em Marx?"},
    {"query": "Explique o que é a 'ação social' para Weber."},

    # ======================================================
    # 🎨 Arte e Música (25)
    # ======================================================
    {"query": "O que foi o Renascimento Italiano na arte?"},
    {"query": "Quem foi Michelangelo e qual sua obra mais famosa?"},
    {"query": "O que é o Impressionismo? Cite 3 artistas."},
    {"query": "Quem foi Vincent van Gogh?"},
    {"query": "O que é o Cubismo? Quem foi Picasso?"},
    {"query": "Explique o que é o Surrealismo. Cite Salvador Dalí."},
    {"query": "O que foi o movimento Bauhaus?"},
    {"query": "Quem foi Frida Kahlo e qual o tema de sua arte?"},
    {"query": "O que é a arte Abstrata?"},
    {"query": "O que foi a 'Pop Art'? Cite Andy Warhol."},
    {"query": "O que é a Semana de Arte Moderna de 1922 no Brasil?"},
    {"query": "Quem foi Tarsila do Amaral?"},
    {"query": "O que é música clássica? Cite Mozart e Beethoven."},
    {"query": "O que é o período Barroco na música? Cite Bach."},
    {"query": "O que é Jazz? Onde surgiu?"},
    {"query": "Quem foi Louis Armstrong?"},
    {"query": "O que é o Blues e qual sua origem?"},
    {"query": "O que foi a Bossa Nova? Cite Tom Jobim."},
    {"query": "Quem foram os Beatles e qual seu impacto na música?"},
    {"query": "O que é o Rock and Roll? Cite Elvis Presley."},
    {"query": "O que é Hip Hop e seus quatro elementos?"},
    {"query": "O que é uma escala musical?"},
    {"query": "Diferencie música erudita de música popular."},
    {"query": "O que é um 'riff' na música?"},
    {"query": "O que é 'harmonia' e 'melodia'?"},

    # ======================================================
    # ⚖️ Direito e Política (25)
    # ======================================================
    {"query": "O que é uma Constituição?"},
    {"query": "Explique os Três Poderes: Executivo, Legislativo e Judiciário."},
    {"query": "O que é o Supremo Tribunal Federal (STF) no Brasil?"},
    {"query": "Diferencie 'Direito Civil' de 'Direito Penal'."},
    {"query": "O que é 'Habeas Corpus'?"},
    {"query": "O que é 'jurisprudência'?"},
    {"query": "Explique o que é uma 'PEC' (Proposta de Emenda à Constituição)."},
    {"query": "O que é o processo de 'impeachment'?"},
    {"query": "Diferencie 'monarquia' de 'república'."},
    {"query": "O que é 'democracia'?"},
    {"query": "O que é o 'presidencialismo' e o 'parlamentarismo'?"},
    {"query": "O que é o Tribunal Penal Internacional?"},
    {"query": "O que são 'Direitos Humanos'?"},
    {"query": "Explique o que é 'Direito do Consumidor'."},
    {"query": "O que é um 'contrato' na visão jurídica?"},
    {"query": "O que é 'pessoa física' e 'pessoa jurídica'?"},
    {"query": "O que é a ONU (Organização das Nações Unidas)?"},
    {"query": "O que é um 'plebiscito' e um 'referendo'?"},
    {"query": "Explique o que é 'imunidade parlamentar'."},
    {"query": "O que é 'crime de responsabilidade'?"},
    {"query": "O que é o 'Ministério Público'?"},
    {"query": "O que é a 'Advocacia-Geral da União' (AGU)?"},
    {"query": "O que é um 'inquérito policial'?"},
    {"query": "Diferencie 'acusado' de 'condenado'."},
    {"query": "O que é o 'trânsito em julgado'?"},

    # ======================================================
    # 🎬 Cinema e Cultura Pop (25)
    # ======================================================
    {"query": "Quem é considerado o 'pai do cinema'?"},
    {"query": "O que foi o movimento 'Nouvelle Vague' no cinema francês?"},
    {"query": "Quem é o diretor Martin Scorsese? Cite 3 filmes dele."},
    {"query": "Resuma o enredo do filme 'O Poderoso Chefão'."},
    {"query": "Quem é Quentin Tarantino e qual seu estilo de direção?"},
    {"query": "O que é o 'Universo Cinematográfico Marvel' (MCU)?"},
    {"query": "Explique o que é um 'blockbuster' no cinema."},
    {"query": "O que é o 'Prêmio Oscar'?"},
    {"query": "Quem é Steven Spielberg? Cite 3 filmes famosos."},
    {"query": "O que é o 'Cinema Novo' no Brasil?"},
    {"query": "Resuma o filme 'Cidade de Deus'."},
    {"query": "O que é um 'roteiro' (script) de filme?"},
    {"query": "Diferencie 'diretor' de 'produtor' no cinema."},
    {"query": "O que é 'CGI' (Computed-Generated Imagery)?"},
    {"query": "Resuma a saga 'Star Wars'."},
    {"query": "Resuma a saga 'O Senhor dos Anéis'."},
    {"query": "Quem é o personagem 'Coringa' e por que é famoso?"},
    {"query": "O que é a 'Pixar' e qual foi seu primeiro longa-metragem?"},
    {"query": "Quem é Hayao Miyazaki e o Studio Ghibli?"},
    {"query": "O que é um 'cliffhanger' em uma série ou filme?"},
    {"query": "O que é um 'remake' e um 'reboot'?"},
    {"query": "Quem é o 'Batman'? Qual sua história de origem?"},
    {"query": "O que é 'streaming' de vídeo? Cite 3 plataformas."},
    {"query": "O que é um 'anime' e um 'mangá'?"},
    {"query": "Resuma a série 'Game of Thrones'."},

    # ======================================================
    # 🍳 Culinária e Gastronomia (25)
    # ======================================================
    {"query": "Como fazer um molho bechamel básico?"},
    {"query": "O que é 'refogar' na culinária?"},
    {"query": "Quais são os 5 sabores básicos do paladar humano?"},
    {"query": "O que é 'umami'?"},
    {"query": "Como cozinhar arroz branco perfeitamente?"},
    {"query": "Receita de 'carbonara' tradicional italiano."},
    {"query": "Diferencie 'grelhar', 'fritar' e 'assar'."},
    {"query": "O que é 'banho-maria'?"},
    {"query": "O que é um 'mirepoix' clássico na culinária francesa?"},
    {"query": "Como fazer um vinagrete simples?"},
    {"query": "O que é fermentação na panificação?"},
    {"query": "Quais são os principais cortes de carne bovina para churrasco?"},
    {"query": "Como dessalgar bacalhau corretamente?"},
    {"query": "O que é a culinária 'fusion'?"},
    {"query": "Quais os ingredientes da 'feijoada' tradicional brasileira?"},
    {"query": "O que é 'branquear' legumes?"},
    {"query": "Como fazer uma omelete francesa clássica?"},
    {"query": "O que é um 'risoto' e qual o arroz correto para usá-lo?"},
    {"query": "O que é 'confitar'?"},
    {"query": "Como temperar um bife simples?"},
    {"query": "O que é 'emulsão' na cozinha? Dê um exemplo."},
    {"query": "Receita de 'guacamole' mexicano."},
    {"query": "O que é 'mise en place' e qual sua importância?"},
    {"query": "O que é 'sous-vide'?"},
    {"query": "Como clarificar manteiga?"},

    # ======================================================
    # 🌌 Astronomia e Exploração Espacial (25)
    # ======================================================
    {"query": "Qual a diferença entre um planeta e uma estrela?"},
    {"query": "Descreva o Sistema Solar, listando os planetas."},
    {"query": "O que é um buraco negro?"},
    {"query": "O que é o 'Big Bang'?"},
    {"query": "O que é a Via Láctea?"},
    {"query": "O que é uma 'supernova'?"},
    {"query": "Diferencie 'meteoro', 'meteorito' e 'meteoroide'."},
    {"query": "O que é uma 'nebulosa'?"},
    {"query": "O que é a 'Estação Espacial Internacional' (ISS)?"},
    {"query": "O que foi o 'Projeto Apollo'?"},
    {"query": "Quem foi o primeiro homem a pisar na Lua?"},
    {"query": "O que são os rovers de Marte, como o 'Curiosity'?"},
    {"query": "O que é o Telescópio Espacial Hubble?"},
    {"query": "Qual a missão do Telescópio Espacial James Webb?"},
    {"query": "O que é 'matéria escura'?"},
    {"query": "O que é 'energia escura'?"},
    {"query": "O que é um 'ano-luz'?"},
    {"query": "Como as estrelas produzem energia?"},
    {"query": "O que é um 'exoplaneta'?"},
    {"query": "Descreva as fases da Lua."},
    {"query": "O que causa os eclipses solares e lunares?"},
    {"query": "O que é o 'Cinturão de Kuiper'?"},
    {"query": "O que é a 'SpaceX' e quem é Elon Musk?"},
    {"query": "O que é a 'gravidade zero' (microgravidade)?"},
    {"query": "Qual a importância de Júpiter para o Sistema Solar?"},

    # ======================================================
    # 🔁 Questões Transversais (Complexas) (25)
    # ======================================================
    {"query": "Discuta as implicações éticas (Filosofia) e legais (Direito) do uso de IA (IA) em sistemas de justiça criminal, abordando o viés algorítmico."},
    {"query": "Como as mudanças climáticas (Geografia) estão impactando o agronegócio (Agro), qual o papel da IoT (IoT) na mitigação, e como isso afeta os preços das commodities (Economia)?"},
    {"query": "Descreva como algoritmos de Machine Learning (IA) podem ser usados para analisar dados de sequenciamento de DNA (Biologia), e quais os desafios de infraestrutura (Redes) para processar esses dados."},
    {"query": "Explique a Reação de Maillard (Química) em termos moleculares, como ela é aplicada na gastronomia (Culinária) para criar sabor, e como o corpo humano (Biologia) metaboliza os produtos finais."},
    {"query": "Como os princípios da relatividade geral (Física) afetam a precisão dos sistemas de GPS (Redes/Astronomia) e qual a matemática (Matemática) envolvida na correção desses desvios?"},
    {"query": "O que é arte generativa? Explique como algoritmos (Programação) e modelos de IA (IA) como StyleGAN podem criar novas estéticas (Arte) e discuta o conceito de autoria (Filosofia/Direito)."},
    {"query": "Descreva a evolução da criptografia desde a cifra de César (História) até o SSL/TLS (Redes), e qual o papel da matemática (Matemática) na segurança moderna."},
    {"query": "Analise o conceito de 'angústia' no existencialismo (Filosofia) e compare com sua representação em personagens de Dostoievski (Literatura) e suas bases neurobiológicas (Biologia)."},
    {"query": "Como o cinema (Cinema) foi usado como ferramenta de propaganda política (Política) durante a Segunda Guerra Mundial (História) tanto pelos Aliados quanto pelo Eixo?"},
    {"query": "Desenvolva um modelo de negócios (Economia) para uma startup que usa drones (IoT) e visão computacional (IA) para detectar pragas na agricultura (Agro), calculando o ROI para o fazendeiro."},
    {"query": "Explique a relação matemática (Matemática) entre as frequências das notas musicais (Música) na escala temperada e como os harmônicos (Física) determinam o timbre de um instrumento."},
    {"query": "Discuta os desafios legais (Direito) e econômicos (Economia) da exploração de recursos naturais (Geografia) na Amazônia, balanceando desenvolvimento e preservação ambiental."},
    {"query": "Quais são os principais desafios técnicos (Redes) e legais (Direito) na implementação de sistemas de vigilância em massa usando reconhecimento facial (IA)?"},
    {"query": "Descreva o mecanismo químico (Química) de ação de um antibiótico (Saúde) e explique o processo biológico (Biologia) da resistência bacteriana."},
    {"query": "Como a Rota da Seda (História) influenciou a gastronomia (Culinária) europeia e asiática através da introdução de novas especiarias (Biologia/Química)?"},
    {"query": "O que é 'High-Frequency Trading' (HFT)? Explique os algoritmos (Programação) usados e discuta o impacto na volatilidade do mercado (Economia)."},
    {"query": "Como sensores baseados em espectroscopia (Física/Química) podem ser integrados em dispositivos IoT (IoT) para análise em tempo real da composição do solo (Agro)?"},
    {"query": "Discuta o Paradoxo de Fermi (Astronomia) e suas implicações filosóficas (Filosofia) sobre a singularidade da vida humana."},
    {"query": "Analise o fenômeno das 'bolhas sociais' (Sociologia) criadas por algoritmos de recomendação (IA) em redes sociais (Redes) e seu impacto na polarização política (Política)."},
    {"query": "Explique o papel do cálculo (Matemática), álgebra linear (Matemática) e estatística (Matemática) no treinamento de uma rede neural profunda (IA)."},
    {"query": "Qual o impacto geopolítico (Política) e econômico (Economia) do controle sobre rotas marítimas estratégicas, como o Canal de Suez (Geografia)?"},
    {"query": "Como os avanços em neurociência (Biologia) e IA (IA) estão influenciando a forma como o cinema (Cinema) retrata a consciência e a identidade?"},
    {"query": "Descreva o impacto da Peste Negra (História) na estrutura social e econômica (Sociologia/Economia) da Europa medieval e compare com a resposta global à pandemia de COVID-19 (Saúde)."},
    {"query": "Quais são os desafios químicos (Química) e legais (Direito) associados ao descarte de lixo eletrônico (Programação/Redes) e seu impacto ambiental (Geografia)?"},
    {"query": "Compare o conceito de 'entropia' na física (Física) com seu uso em teoria da informação (Matemática/Redes) e discuta suas implicações filosóficas (Filosofia)."},
]

# ==========================================================
# Classe Locust
# ==========================================================
class RouterUser(HttpUser):
    wait_time = between(1, 3)
    host = "http://llm_router_api:8000"

    @task
    def send_query(self):
        q = random.choice(QUERIES)
        payload = {
            "query": q["query"],
            "enable_rag_for_answer": False,
            "max_tokens": 2048,
            "temperature": 0.3
        }
        self.client.post("/query", json=payload)