global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # -----------------------------------
  # Coleta do LLM Router API
  # -----------------------------------
  - job_name: "llm_router_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["llm_router_api:8000"]

  # -----------------------------------
  # Coleta do Prometheus (auto-monitoramento)
  # -----------------------------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # -----------------------------------
  # Coleta do NSGA Updater
  # -----------------------------------
  - job_name: 'nsga_updater'
    static_configs:
      - targets: ['nsga_updater:8000']
