# Objective: PostgreSQL baseline of the ARISTO schema (Cloud SQL): the 31 production tables plus the three the
# code writes but production never had.
"""Baseline PostgreSQL do ARISTO.

Gerada por reflexão do esquema de produção do MariaDB (dump de 26/09/2026, 31 tabelas) e traduzida:
AUTO_INCREMENT -> IDENTITY, LONGTEXT -> TEXT, LONGBLOB -> BYTEA, ENUM -> VARCHAR + CHECK, FLOAT/DOUBLE -> DOUBLE
PRECISION (a cópia não perde nada), TIMESTAMP/DATETIME -> TIMESTAMPTZ (sessão em UTC), TINYINT -> SMALLINT, e
BOOLEAN onde o código grava bool do Python ou lê com ``CASE WHEN coluna`` (shadow_evaluations.executada,
painel_uniforme, teria_abstido; judge_calibration.was_cached). Colunas em minúsculas (m2, n_pop, n_gen); índices
com nome por tabela (no PostgreSQL o nome é único no schema); ON UPDATE CURRENT_TIMESTAMP vira o trigger
``set_col_now``.

Acréscimos sobre produção: ``user_feedback``, ``openrouter_exploration_stats`` e ``correlation_history`` (o código
grava nelas; em produção não existiam e as gravações falhavam); ``UNIQUE (modality, model)`` em ``nsga_weights``
(o upsert dos pesos não tinha chave e só inseria); e-mail do especialista único sem diferenciar maiúsculas.

Revision ID: pg_0001_baseline
Revises:
Create Date: 2026-09-26
"""

import sqlalchemy as sa
from alembic import op

revision = "pg_0001_baseline"
down_revision = None
branch_labels = None
depends_on = None

DDL = [
    """
CREATE OR REPLACE FUNCTION set_col_now() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW := jsonb_populate_record(NEW, jsonb_build_object(TG_ARGV[0], now()));
  RETURN NEW;
END $$
    """,
    """
CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(255) NOT NULL,
    PRIMARY KEY (version_num)
)
    """,
    """
CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor VARCHAR(128) NOT NULL,
    action VARCHAR(128) NOT NULL,
    resource VARCHAR(128) NOT NULL,
    tenant_id VARCHAR(128),
    metadata TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_audit_log_action_created_at ON audit_log (action, created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_audit_log_tenant_id_created_at ON audit_log (tenant_id, created_at)
    """,
    """
CREATE TABLE IF NOT EXISTS bandit_context_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    context_label VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    last_update TIMESTAMPTZ DEFAULT now(),
    avg_reward DOUBLE PRECISION DEFAULT 0,
    count INTEGER DEFAULT 0,
    var DOUBLE PRECISION DEFAULT 0,
    m2 DOUBLE PRECISION DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uq_bandit_context_stats_context_label_model UNIQUE (context_label, model)
)
    """,
    """
CREATE TRIGGER trg_bandit_context_stats_last_update BEFORE UPDATE ON bandit_context_stats FOR EACH ROW EXECUTE FUNCTION set_col_now('last_update')
    """,
    """
CREATE TABLE IF NOT EXISTS ema_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model VARCHAR(255) NOT NULL,
    modality VARCHAR(10) DEFAULT 'text' NOT NULL CHECK (modality IN ('text', 'vision', 'multimodal')),
    updated_at TIMESTAMPTZ DEFAULT now(),
    semantics VARCHAR(16) DEFAULT 'rubric_v1' NOT NULL,
    ema_latency DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ema_cost DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ema_quality DOUBLE PRECISION DEFAULT 0 NOT NULL,
    ema_alignment DOUBLE PRECISION DEFAULT 0 NOT NULL,
    policy_namespace VARCHAR(64) DEFAULT '' NOT NULL,
    updates INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_ema_history_model_modality_semantics_policy_namespace UNIQUE (model, modality, semantics, policy_namespace)
)
    """,
    """
CREATE TRIGGER trg_ema_history_updated_at BEFORE UPDATE ON ema_history FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS ema_history_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    modality VARCHAR(10) DEFAULT 'text' NOT NULL CHECK (modality IN ('text', 'vision', 'multimodal')),
    model VARCHAR(255) NOT NULL,
    ema_latency DOUBLE PRECISION NOT NULL,
    ema_cost DOUBLE PRECISION NOT NULL,
    ema_quality DOUBLE PRECISION NOT NULL,
    ema_alignment DOUBLE PRECISION NOT NULL,
    update_num INTEGER DEFAULT 0 NOT NULL,
    semantics VARCHAR(16) DEFAULT 'rubric_v1' NOT NULL,
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_ema_history_log_created_at ON ema_history_log (created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_ema_history_log_created_at ON ema_history_log (created_at)
    """,
    """
CREATE TABLE IF NOT EXISTS eval_run_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id VARCHAR(64) NOT NULL,
    prompt_text TEXT,
    model VARCHAR(255),
    quality DOUBLE PRECISION,
    latency_s DOUBLE PRECISION,
    cost_usd DOUBLE PRECISION,
    metadata_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_eval_run_results_run_id_created_at ON eval_run_results (run_id, created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_eval_run_results_run_id_model ON eval_run_results (run_id, model)
    """,
    """
CREATE TABLE IF NOT EXISTS eval_runs (
    id VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    policy_version VARCHAR(128),
    tenant_id VARCHAR(128),
    notes TEXT,
    prompts_json TEXT,
    summary_json TEXT,
    metadata_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_eval_runs_status_created_at ON eval_runs (status, created_at)
    """,
    """
CREATE TRIGGER trg_eval_runs_updated_at BEFORE UPDATE ON eval_runs FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS expert_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    phone VARCHAR(32),
    enabled SMALLINT DEFAULT 1 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_expert_accounts_email UNIQUE (email)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_expert_accounts_enabled_created_at ON expert_accounts (enabled, created_at)
    """,
    """
CREATE TRIGGER trg_expert_accounts_updated_at BEFORE UPDATE ON expert_accounts FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS expert_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    expert_id VARCHAR(128) NOT NULL,
    benchmark_id VARCHAR(128) NOT NULL,
    theme VARCHAR(128) NOT NULL,
    query_text TEXT,
    answer TEXT,
    reference TEXT,
    eval_run_id VARCHAR(64),
    judge_quality DOUBLE PRECISION,
    quality_score DOUBLE PRECISION NOT NULL,
    rubric_json TEXT,
    notes TEXT,
    status VARCHAR(32) DEFAULT 'submitted' NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_expert_assessments_expert_id_benchmark_id_eval_run_id UNIQUE (expert_id, benchmark_id, eval_run_id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_expert_assessments_eval_run_id ON expert_assessments (eval_run_id)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_expert_assessments_theme_created_at ON expert_assessments (theme, created_at)
    """,
    """
CREATE TRIGGER trg_expert_assessments_updated_at BEFORE UPDATE ON expert_assessments FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS expert_profiles (
    user_id VARCHAR(128) NOT NULL,
    display_name VARCHAR(255),
    theme_ids TEXT,
    credentials_note TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (user_id)
)
    """,
    """
CREATE TRIGGER trg_expert_profiles_updated_at BEFORE UPDATE ON expert_profiles FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS judge_calibration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    judge_model VARCHAR(255) NOT NULL,
    query_hash VARCHAR(64) NOT NULL,
    predicted_score DOUBLE PRECISION NOT NULL,
    was_cached BOOLEAN DEFAULT false,
    cache_hit_count INTEGER DEFAULT 0,
    calibration_score DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_judge_calibration_created_at ON judge_calibration (created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_judge_calibration_judge_model ON judge_calibration (judge_model)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_judge_calibration_query_hash ON judge_calibration (query_hash)
    """,
    """
CREATE TABLE IF NOT EXISTS judge_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    query TEXT,
    answer TEXT,
    judge_model VARCHAR(255),
    score_before DOUBLE PRECISION,
    fallback_model VARCHAR(255),
    score_after DOUBLE PRECISION,
    event_type VARCHAR(50),
    modality VARCHAR(32) DEFAULT 'text',
    image_hash VARCHAR(128),
    rubric_json TEXT,
    delivery_level DOUBLE PRECISION,
    correlation_id VARCHAR(64),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_judge_logs_correlation_id ON judge_logs (correlation_id)
    """,
    """
CREATE TABLE IF NOT EXISTS judge_performance_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    judge_model VARCHAR(255) NOT NULL,
    avg_score DOUBLE PRECISION DEFAULT 0,
    avg_latency DOUBLE PRECISION DEFAULT 0,
    avg_cost DOUBLE PRECISION DEFAULT 0,
    consistency DOUBLE PRECISION DEFAULT 0,
    fitness DOUBLE PRECISION DEFAULT 0,
    window_start TIMESTAMPTZ DEFAULT now(),
    window_end TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE TABLE IF NOT EXISTS learned_state (
    chave VARCHAR(191) NOT NULL,
    atualizado_em TIMESTAMPTZ DEFAULT now(),
    valor TEXT NOT NULL,
    PRIMARY KEY (chave)
)
    """,
    """
CREATE TRIGGER trg_learned_state_atualizado_em BEFORE UPDATE ON learned_state FOR EACH ROW EXECUTE FUNCTION set_col_now('atualizado_em')
    """,
    """
CREATE TABLE IF NOT EXISTS model_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now() NOT NULL,
    model VARCHAR(255) NOT NULL,
    modality VARCHAR(32) DEFAULT 'text' NOT NULL,
    latency_ms DOUBLE PRECISION DEFAULT 0 NOT NULL,
    cost_usd DOUBLE PRECISION DEFAULT 0 NOT NULL,
    cost_per_1k DOUBLE PRECISION DEFAULT 0,
    quality_score DOUBLE PRECISION DEFAULT 0 NOT NULL,
    tokens_in INTEGER,
    tokens_out INTEGER,
    embedding_dim INTEGER,
    vision_usage SMALLINT DEFAULT 0,
    fitness DOUBLE PRECISION DEFAULT 0 NOT NULL,
    generation INTEGER DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_model_metrics_timestamp ON model_metrics (timestamp)
    """,
    """
CREATE TABLE IF NOT EXISTS model_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model VARCHAR(255) NOT NULL,
    cost_input_1k DOUBLE PRECISION DEFAULT 0,
    cost_output_1k DOUBLE PRECISION DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_model_pricing_model UNIQUE (model)
)
    """,
    """
CREATE TRIGGER trg_model_pricing_updated_at BEFORE UPDATE ON model_pricing FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS model_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model VARCHAR(255) NOT NULL,
    is_active SMALLINT DEFAULT 1,
    modality VARCHAR(10) DEFAULT 'text' NOT NULL CHECK (modality IN ('text', 'vision', 'multimodal')),
    provider VARCHAR(64) DEFAULT 'ollama' NOT NULL,
    max_context INTEGER DEFAULT 4096,
    cost_per_1k DOUBLE PRECISION DEFAULT 0,
    PRIMARY KEY (id)
)
    """,
    """
CREATE TABLE IF NOT EXISTS nsga_meta_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT now(),
    trial_id INTEGER NOT NULL,
    modality VARCHAR(32) DEFAULT 'text' NOT NULL,
    n_pop INTEGER NOT NULL,
    n_gen INTEGER NOT NULL,
    cxpb DOUBLE PRECISION NOT NULL,
    mutpb DOUBLE PRECISION NOT NULL,
    eta_c DOUBLE PRECISION NOT NULL,
    eta_m DOUBLE PRECISION NOT NULL,
    eff_mean DOUBLE PRECISION NOT NULL,
    eff_std DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (id)
)
    """,
    """
CREATE TABLE IF NOT EXISTS nsga_params (
    id INTEGER NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now(),
    modality VARCHAR(32) DEFAULT 'text' NOT NULL,
    n_pop INTEGER DEFAULT 40 NOT NULL,
    n_gen INTEGER DEFAULT 20 NOT NULL,
    cxpb DOUBLE PRECISION DEFAULT 0.9 NOT NULL,
    mutpb DOUBLE PRECISION DEFAULT 0.1 NOT NULL,
    eta_c DOUBLE PRECISION DEFAULT 20 NOT NULL,
    eta_m DOUBLE PRECISION DEFAULT 20 NOT NULL,
    PRIMARY KEY (id)
)
    """,
    """
CREATE TRIGGER trg_nsga_params_updated_at BEFORE UPDATE ON nsga_params FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS nsga_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model VARCHAR(255) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now(),
    modality VARCHAR(32) DEFAULT 'text' NOT NULL,
    weight DOUBLE PRECISION DEFAULT 0 NOT NULL,
    PRIMARY KEY (id)
)
    """,
    """
CREATE TRIGGER trg_nsga_weights_updated_at BEFORE UPDATE ON nsga_weights FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS policy_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version VARCHAR(128) NOT NULL,
    description TEXT,
    config_json TEXT,
    is_active SMALLINT DEFAULT 0 NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_policy_versions_version UNIQUE (version)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_policy_versions_is_active ON policy_versions (is_active)
    """,
    """
CREATE TRIGGER trg_policy_versions_updated_at BEFORE UPDATE ON policy_versions FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS query_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    query_text TEXT,
    chosen_model VARCHAR(255) DEFAULT 'unknown' NOT NULL,
    modality VARCHAR(32) DEFAULT 'text',
    image_provided SMALLINT DEFAULT 0,
    answer TEXT,
    image_output_b64 TEXT,
    query_embedding BYTEA,
    answer_embedding BYTEA,
    quality DOUBLE PRECISION,
    latency_s DOUBLE PRECISION,
    cost_per_1k DOUBLE PRECISION,
    reward DOUBLE PRECISION,
    context_label VARCHAR(64),
    raw_payload TEXT,
    quality_source VARCHAR(32) DEFAULT 'unknown',
    judge_sampled SMALLINT DEFAULT 0,
    predicted_error_prob DOUBLE PRECISION,
    quality_semantics VARCHAR(16) DEFAULT 'rubric_v1' NOT NULL,
    q_tech DOUBLE PRECISION,
    q_calibrado DOUBLE PRECISION,
    p_entrega DOUBLE PRECISION,
    detected_complexity VARCHAR(16),
    confidence_score DOUBLE PRECISION,
    confidence_band VARCHAR(16),
    abstained SMALLINT DEFAULT 0,
    abstain_reason VARCHAR(64),
    grounded SMALLINT DEFAULT 0,
    verification_status VARCHAR(32),
    knowledge_version VARCHAR(255),
    review_status VARCHAR(32),
    estimated_cost_usd DOUBLE PRECISION,
    tenant_id VARCHAR(128),
    decision_json TEXT,
    correlation_id VARCHAR(64),
    participant VARCHAR(256),
    episode_id VARCHAR(128),
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    reasoning_tokens INTEGER,
    finish_reason VARCHAR(32),
    trace_json TEXT,
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_query_log_created_at ON query_log (created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_query_log_chosen_model_created_at ON query_log (chosen_model, created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_query_log_correlation_id ON query_log (correlation_id)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_query_log_participant_created_at ON query_log (participant, created_at)
    """,
    """
CREATE TABLE IF NOT EXISTS rbac_user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id VARCHAR(128) NOT NULL,
    role_name VARCHAR(64) NOT NULL,
    tenant_id VARCHAR(128),
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_rbac_user_roles_user_id_role_name_tenant_id UNIQUE (user_id, role_name, tenant_id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_rbac_user_roles_role_name ON rbac_user_roles (role_name)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_rbac_user_roles_user_id ON rbac_user_roles (user_id)
    """,
    """
CREATE TABLE IF NOT EXISTS request_failures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    correlation_id VARCHAR(64),
    tenant_id VARCHAR(128),
    participant VARCHAR(256),
    episode_id VARCHAR(128),
    route_path VARCHAR(64),
    status_code INTEGER NOT NULL,
    category VARCHAR(64),
    model VARCHAR(255),
    detail_json TEXT,
    query_text TEXT,
    modality VARCHAR(16),
    latency_s DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_request_failures_correlation_id ON request_failures (correlation_id)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_request_failures_tenant_id_created_at ON request_failures (tenant_id, created_at)
    """,
    """
CREATE TABLE IF NOT EXISTS response_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    correlation_id VARCHAR(128),
    tenant_id VARCHAR(128),
    query_text TEXT,
    answer TEXT,
    chosen_model VARCHAR(255),
    confidence_score DOUBLE PRECISION,
    confidence_band VARCHAR(16),
    grounded SMALLINT DEFAULT 0,
    verification_status VARCHAR(32),
    review_status VARCHAR(32) DEFAULT 'needs_review' NOT NULL,
    review_reason VARCHAR(64),
    reviewer_id VARCHAR(128),
    reviewer_notes TEXT,
    corrected_answer TEXT,
    metadata_json TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_response_reviews_review_status_created_at ON response_reviews (review_status, created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_response_reviews_tenant_id_created_at ON response_reviews (tenant_id, created_at)
    """,
    """
CREATE TRIGGER trg_response_reviews_updated_at BEFORE UPDATE ON response_reviews FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS semantic_cache (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    query_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    modality VARCHAR(32) DEFAULT 'text',
    query_text TEXT,
    answer TEXT,
    model_used VARCHAR(255),
    embedding BYTEA,
    image_output_b64 TEXT,
    PRIMARY KEY (id),
    CONSTRAINT uq_semantic_cache_query_hash UNIQUE (query_hash)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_semantic_cache_modality_query_hash ON semantic_cache (modality, query_hash)
    """,
    """
CREATE TABLE IF NOT EXISTS settings_dynamic (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    setting_key VARCHAR(512) NOT NULL,
    setting_value TEXT,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_settings_dynamic_setting_key UNIQUE (setting_key)
)
    """,
    """
CREATE TRIGGER trg_settings_dynamic_updated_at BEFORE UPDATE ON settings_dynamic FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS shadow_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    episode_id VARCHAR(128),
    participante VARCHAR(256),
    tenant VARCHAR(128),
    caso SMALLINT,
    estrato TEXT,
    p_nominal DOUBLE PRECISION,
    executada BOOLEAN DEFAULT false NOT NULL,
    motivo_corte VARCHAR(40),
    modelo VARCHAR(160) NOT NULL,
    provedor VARCHAR(40),
    regiao VARCHAR(40),
    versao_modelo VARCHAR(200),
    papel VARCHAR(10) NOT NULL,
    regime_entrega VARCHAR(20),
    p_atribuicao DOUBLE PRECISION,
    escores_juizes TEXT,
    escore_agregado DOUBLE PRECISION,
    painel TEXT,
    painel_uniforme BOOLEAN,
    teria_abstido BOOLEAN,
    custo_usd DOUBLE PRECISION,
    latencia_s DOUBLE PRECISION,
    tokens_entrada INTEGER,
    tokens_saida INTEGER,
    sha256_texto CHAR(64),
    status VARCHAR(40) NOT NULL,
    frozen_run_id VARCHAR(128),
    criado_em TIMESTAMPTZ NOT NULL,
    concluido_em TIMESTAMPTZ,
    p_candidata DOUBLE PRECISION,
    PRIMARY KEY (id)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_shadow_evaluations_request_id ON shadow_evaluations (request_id)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_shadow_evaluations_status ON shadow_evaluations (status)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_shadow_evaluations_tenant_criado_em ON shadow_evaluations (tenant, criado_em)
    """,
    """
CREATE TABLE IF NOT EXISTS shadow_suspensions (
    chave VARCHAR(200) NOT NULL,
    motivo VARCHAR(40) NOT NULL,
    tenant VARCHAR(128),
    inicio TIMESTAMPTZ NOT NULL,
    fim TIMESTAMPTZ,
    PRIMARY KEY (chave)
)
    """,
    """
CREATE TABLE IF NOT EXISTS tenant_budgets (
    tenant_id VARCHAR(128) NOT NULL,
    daily_usd_limit DOUBLE PRECISION DEFAULT 0 NOT NULL,
    monthly_usd_limit DOUBLE PRECISION DEFAULT 0 NOT NULL,
    enabled SMALLINT DEFAULT 1 NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (tenant_id)
)
    """,
    """
CREATE TRIGGER trg_tenant_budgets_updated_at BEFORE UPDATE ON tenant_budgets FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS tenant_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id VARCHAR(128) NOT NULL,
    day_key DATE NOT NULL,
    month_key VARCHAR(7) NOT NULL,
    requests INTEGER DEFAULT 0 NOT NULL,
    tokens_in BIGINT DEFAULT 0 NOT NULL,
    tokens_out BIGINT DEFAULT 0 NOT NULL,
    cost_usd DOUBLE PRECISION DEFAULT 0 NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (id),
    CONSTRAINT uq_tenant_usage_tenant_id_day_key UNIQUE (tenant_id, day_key)
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_tenant_usage_tenant_id_month_key ON tenant_usage (tenant_id, month_key)
    """,
    """
CREATE TRIGGER trg_tenant_usage_updated_at BEFORE UPDATE ON tenant_usage FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS user_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id VARCHAR(64),
    query_text TEXT,
    model VARCHAR(255) NOT NULL,
    modality VARCHAR(32) DEFAULT 'text',
    feedback_type VARCHAR(32) NOT NULL,
    rating INTEGER,
    user_quality DOUBLE PRECISION,
    original_quality DOUBLE PRECISION,
    blended_quality DOUBLE PRECISION,
    reward DOUBLE PRECISION,
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_user_feedback_model_created_at ON user_feedback (model, created_at)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_user_feedback_created_at ON user_feedback (created_at)
    """,
    """
CREATE TABLE IF NOT EXISTS openrouter_exploration_stats (
    model VARCHAR(255) PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 0,
    failure_count INTEGER NOT NULL DEFAULT 0,
    mean_reward DOUBLE PRECISION,
    mean_latency_s DOUBLE PRECISION,
    mean_cost_usd DOUBLE PRECISION,
    mean_observed_usd_per_1k DOUBLE PRECISION,
    catalog_prompt_usd_per_1k DOUBLE PRECISION,
    catalog_completion_usd_per_1k DOUBLE PRECISION,
    auto_promoted_at TIMESTAMPTZ,
    blocklisted SMALLINT NOT NULL DEFAULT 0,
    stats_json TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_openrouter_exploration_stats_auto_promoted_at ON openrouter_exploration_stats (auto_promoted_at)
    """,
    """
CREATE TRIGGER trg_openrouter_exploration_stats_updated_at BEFORE UPDATE ON openrouter_exploration_stats FOR EACH ROW EXECUTE FUNCTION set_col_now('updated_at')
    """,
    """
CREATE TABLE IF NOT EXISTS correlation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model VARCHAR(255),
    corr_latency_quality DOUBLE PRECISION,
    corr_cost_quality DOUBLE PRECISION,
    corr_fitness_weights DOUBLE PRECISION,
    r2_mean DOUBLE PRECISION,
    generation INTEGER,
    timestamp TIMESTAMPTZ DEFAULT now()
)
    """,
    """
CREATE INDEX IF NOT EXISTS ix_correlation_history_model_timestamp ON correlation_history (model, timestamp)
    """,
    """
ALTER TABLE nsga_weights ADD CONSTRAINT uq_nsga_weights_modality_model UNIQUE (modality, model)
    """,
    """
CREATE UNIQUE INDEX IF NOT EXISTS uq_expert_accounts_lower_email ON expert_accounts (lower(email))
    """,
]


def upgrade() -> None:
    conn = op.get_bind()
    for comando in DDL:
        conn.execute(sa.text(comando))


def downgrade() -> None:
    raise RuntimeError("baseline: não há downgrade (apagar o banco é uma decisão explícita, não uma migração)")
