# Objective: Judge subsystem code for llm.
"""Run LLM-based answer judging for quality scoring.

This module builds the evaluation prompt used by judge models and parses the
structured score returned by LiteLLM-compatible providers. It is intentionally
small because the higher-level orchestration lives in ``judges/judge.py`` while
this file focuses on prompt construction and synchronous/asynchronous execution.
"""

import asyncio, json
from typing import Dict, Any
from ..settings import settings
from ..rag import retrieve_context
from litellm import completion

RUBRIC_BASE = """
You are a strict evaluator. Score the ASSISTANT answer for the USER question from 0 to 10.
Consider: (1) factual correctness, (2) task completion, (3) clarity & structure, (4) harmful content avoidance.
Return ONLY a JSON object: {"score": <0-10>, "rationale": "<short reason>"}.
"""

def _build_prompt(user_q: str, assistant_a: str, use_rag: bool) -> str:
    """Build the judging prompt sent to the evaluator model.

    Args:
        user_q: Original end-user question.
        assistant_a: Candidate answer generated by the router.
        use_rag: Whether optional retrieved context should be included.

    Returns:
        str: A strict rubric asking the judge model to return JSON only.
    """
    ctx = ""
    if use_rag:
        rag = retrieve_context(user_q)
        if rag:
            ctx = f"CONTEXT (may be useful, optional):\n---\n{rag}\n---\n"
    return f"""{RUBRIC_BASE}
{ctx}
USER QUESTION:
{user_q}

ASSISTANT ANSWER:
{assistant_a}
"""

def _score_sync(user_q: str, assistant_a: str, judge_id: str, use_rag: bool) -> Dict[str, Any]:
    """Run one synchronous LLM judge call and normalize its output.

    The function tolerates malformed judge responses by converting them into a
    low-confidence fallback score rather than raising, which keeps the broader
    judging pipeline resilient.
    """
    prompt = _build_prompt(user_q, assistant_a, use_rag)
    resp = completion(model=settings.JUDGE_LLM_MODEL,
                      messages=[{"role":"user","content": prompt}],
                      temperature=0.0, max_tokens=128)
    text = resp.choices[0].message["content"]
    try:
        j = json.loads(text)
        score = float(j.get("score", 0))
        rationale = str(j.get("rationale", ""))[:300]
    except Exception:
        score = 0.0
        rationale = text[:280]
    score = max(0.0, min(10.0, score))
    return {"judge_id": judge_id, "score": score, "rationale": rationale}

async def score(user_q: str, assistant_a: str, idx: int) -> Dict[str, Any]:
    """Execute one LLM judge in a worker thread.

    Args:
        user_q: Original end-user question.
        assistant_a: Candidate answer under evaluation.
        idx: Judge index used to build a stable judge identifier.

    Returns:
        dict[str, Any]: Normalized judge payload with ``judge_id``, ``score``,
        and ``rationale``.
    """
    judge_id = f"llm_{idx}"
    return await asyncio.to_thread(_score_sync, user_q, assistant_a, judge_id, settings.JUDGE_USE_RAG)
